# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jobs-as-code/main/src/dbt_jobs_as_code/schemas/load_job_schema.json

jobs:
  job1:

    account_id: 70471823560306
    deferring_job_definition_id: null
    project_id: "{{ project_id }}"
    environment_id: "{{ environment_id }}"
    execute_steps:
    - "dbt run --select src_listings"
    execution:
      timeout_seconds: 0
    generate_docs: false
    name: "Dev Testing1"
    run_generate_sources: true
    schedule:
      cron: "0 0 * * 0"
    settings:
      target_name: dev
      threads: 4
    state: 1
    triggers:
      git_provider_webhook: false
      github_webhook: false
      # we can add more complex logic in Jinja based on our variables
      schedule: "{{ env_type == 'dev' }}"